### PR TITLE
Lab Submission Merle Pfau

### PR DESCRIPTION
**Pull request by MerlePfau**

### CODE REVIEW

**Comment by inariksit** [comment]
Can you remove the `.gfo` files, those are generated by the compiler and are not supposed to be under version control.

**Comment by daherb** [comment]
Also, rename your application grammar to include your name. Otherwise it could lead to problems when someone else is submitting a French Doctor grammar

**Comment by daherb** [comment]
There still seems to be one gfo file

**Comment by MerlePfau** [comment]
Hope this works now!

**Pull request merged**
